/// Configuration class holding weighted keyword definitions for topic categorization.
class TopicConfig {
  final String name;
  final List<TopicKeyword> keywords;
  final double threshold;
  final List<String> exclusions;

  const TopicConfig({
    required this.name,
    required this.keywords,
    this.threshold = 2.0,
    this.exclusions = const [],
  });
}

/// A single keyword with an associated weight for topic scoring.
class TopicKeyword {
  final String keyword;
  final double weight;

  const TopicKeyword({
    required this.keyword,
    this.weight = 1.0,
  });
}

/// Configuration class holding static data sources and filtering rules for the app.
/// This centralizes the list of RSS feed URLs to display names, as well as keywords
/// used for filtering content or categorizing articles into topics.
class AppConfig {
  /// A map of core Australian left-wing news outlets' RSS feeds to their display names.
  /// These are considered primary sources for the application's default view.
  static const Map<String, String> coreSources = {
    "https://ancomfed.org/picket-line/feed": "PICKET LINE",
    "https://www.greenleft.org.au/rss.xml": "GREEN LEFT",
    "https://redflag.org.au/rss/": "RED FLAG",
    "https://red-spark.org/tag/australia/feed": "RED SPARK",
    "https://socialismtoday.au/feed": "SOCIALISM TODAY",
    "https://solidarity.net.au/feed": "SOLIDARITY",
    "https://labortribune.net.au/feed": "LABOR TRIBUNE",
    "https://www.wsws.org/en/topics/country/australia/rss.xml": "WORLD SOCIALIST WEB SITE",
    "https://melbacg.au/category/anvil/rss": "THE ANVIL",
    "https://vanguard-cpaml.blogspot.com/rss.xml": "VANGUARD",
    "https://partisanmagazine.org/feed/": "PARTISAN!",
    "https://redantcollective.org/feed": "RED ANT",
    "https://temokalati.wordpress.com/feed": "TEMOKALATI",
    "https://www.thenews.coop/country/oceania/feed": "CO-OP NEWS",
    "https://seqldiww.org/category/australia/feed": "IWW (SOUTH EAST QUEENSLAND)",
    "https://freedomnews.org.uk/tag/australia/feed": "FREEDOM",
    "https://disputesreport.substack.com/feed": "DISPUTES REPORT",
    "https://overland.org.au/latest/feed": "OVERLAND",
    "https://au.spiritofeureka.org/category/fp-roktabs-showcase/feed": "SPIRIT OF EUREKA",
    "https://www.blackpeoplesunion.org/articles/rss.xml": "BLACK PEOPLES UNION",
    "https://www.blackpeoplesunion.org/statements/rss.xml": "BLACK PEOPLES UNION",
    "https://indigenousx.com.au/stories/feed": "INDIGENOUSX",
    "https://www.redblacknotes.com/feed/rss": "RED AND BLACK NOTES",
    "https://cpa.org.au/feed/?post_type=guardian": "THE GUARDIAN (CPA)",
    "https://arena.org.au/feed": "ARENA",
    "https://communist.org.au/feed": "THE COMMUNIST",
    "https://www.auscp.org.au/militant-worker/rss.xml": "MILITANT WORKER",
    "https://koorimail.com/feed": "KOORI MAIL",
    "https://www.3cr.org.au/news.xml": "3CR"
  };

  /// A map of global political and economic publications not specific to Australia.
  static const Map<String, String> globalSources = {
    "https://jacobin.com/feed": "JACOBIN",
    "https://themilitant.com/feed": "THE MILITANT",
    "https://www.counterpunch.org/feed": "COUNTER PUNCH"
  };

  /// Extended list of sources that may be loaded or displayed in advanced views.
  static const Map<String, String> extendedSources = {
    "https://michaelwest.com.au/category/latest-posts/feed/": "MICHAEL WEST",
    "http://feeds.feedburner.com/IndependentAustralia": "INDEPENDENT AUSTRALIA",
    "https://theconversation.com/topics/australia-64/articles.atom": "THE CONVERSATION",
    "https://www.theguardian.com/australia-news/australian-trade-unions/rss": "THE GUARDIAN (GNM)",
  };

  /// Keywords used to filter articles relevant to Australian regions and politics.
  /// Used by the parser to prioritize or tag local news items.
  static const List<String> auKeywords = [
    "australia", "australian", "new south wales", "nsw", "sydney", "victoria", "vic", "melbourne",
    "queensland", "qld", "brisbane", "western australia", "wa", "perth", "south australia", "sa",
    "adelaide", "tasmania", "tas", "hobart", "act", "canberra", "nt", "darwin"
  ];

  /// Keywords indicating theoretical, historical, or archival content.
  /// These help categorize deeper reads rather than breaking news.
  static const List<String> theoryKeywords = [
    "book review", "reviewed by", "reading group", "theory of", "centenary of", "anniversary of",
    "historical perspective", "the legacy of", "marxist theory", "obituary", "in memoriam",
    "historical archive", "pamphlet", "from the archives", "essays on", "reflections on",
    "dialectics", "philosophical", "critique of",
  ];

  /// Categorization logic mapping broad topic headers to their corresponding weighted keywords.
  /// Uses a scoring system where:
  ///   - Title matches are weighted 3x
  ///   - Description matches are weighted 1x
  ///   - Multi-word phrases get bonus weight
  ///   - Articles must meet a minimum threshold to be tagged
  ///   - Exclusion keywords can prevent misclassification
  static final List<TopicConfig> topics = [
    const TopicConfig(
      name: "ECONOMY",
      threshold: 2.0,
      exclusions: ["funeral", "memorial", "obituary", "death"],
      keywords: [
        TopicKeyword(keyword: "inflation", weight: 2.0),
        TopicKeyword(keyword: "cost of living", weight: 3.0),
        TopicKeyword(keyword: "cost of living crisis", weight: 3.0),
        TopicKeyword(keyword: "tax", weight: 1.5),
        TopicKeyword(keyword: "wealth", weight: 1.5),
        TopicKeyword(keyword: "budget", weight: 1.5),
        TopicKeyword(keyword: "recession", weight: 2.0),
        TopicKeyword(keyword: "housing", weight: 2.0),
        TopicKeyword(keyword: "rent", weight: 1.5),
        TopicKeyword(keyword: "mortgage", weight: 2.0),
        TopicKeyword(keyword: "economy", weight: 1.0),
        TopicKeyword(keyword: "economic", weight: 1.0),
        TopicKeyword(keyword: "market", weight: 1.0),
        TopicKeyword(keyword: "trade", weight: 1.0),
      ],
    ),
    const TopicConfig(
      name: "ENVIRONMENT",
      threshold: 2.0,
      exclusions: ["sport", "recreation", "hiking", "camping"],
      keywords: [
        TopicKeyword(keyword: "climate crisis", weight: 3.0),
        TopicKeyword(keyword: "climate emergency", weight: 3.0),
        TopicKeyword(keyword: "global warming", weight: 2.5),
        TopicKeyword(keyword: "renewable", weight: 2.0),
        TopicKeyword(keyword: "renewable energy", weight: 2.5),
        TopicKeyword(keyword: "solar", weight: 1.5),
        TopicKeyword(keyword: "wind energy", weight: 2.0),
        TopicKeyword(keyword: "biodiversity", weight: 2.0),
        TopicKeyword(keyword: "deforestation", weight: 2.0),
        TopicKeyword(keyword: "emissions", weight: 1.5),
        TopicKeyword(keyword: "coal", weight: 1.5),
        TopicKeyword(keyword: "gas", weight: 1.0),
        TopicKeyword(keyword: "fossil fuel", weight: 2.0),
        TopicKeyword(keyword: "fossil fuels", weight: 2.0),
        TopicKeyword(keyword: "environment", weight: 1.0),
        TopicKeyword(keyword: "environmental", weight: 1.0),
        TopicKeyword(keyword: "climate", weight: 1.0),
        TopicKeyword(keyword: "wildfire", weight: 1.5),
        TopicKeyword(keyword: "bushfire", weight: 1.5),
      ],
    ),
    const TopicConfig(
      name: "FIRST NATIONS",
      threshold: 1.5,
      exclusions: ["sport", "cricket", "football", "rugby"],
      keywords: [
        TopicKeyword(keyword: "treaty", weight: 2.5),
        TopicKeyword(keyword: "voice", weight: 1.5),
        TopicKeyword(keyword: "maiden parliamentary speech", weight: 2.0),
        TopicKeyword(keyword: "first nations", weight: 2.0),
        TopicKeyword(keyword: "indigenous", weight: 1.5),
        TopicKeyword(keyword: "aboriginal", weight: 1.5),
        TopicKeyword(keyword: "torres strait islander", weight: 2.0),
        TopicKeyword(keyword: "torres strait islanders", weight: 2.0),
        TopicKeyword(keyword: "native title", weight: 2.0),
        TopicKeyword(keyword: "stolen generations", weight: 2.0),
        TopicKeyword(keyword: "genocide", weight: 2.0),
        TopicKeyword(keyword: "survivors", weight: 1.0),
        TopicKeyword(keyword: "national", weight: 0.5),
      ],
    ),
    const TopicConfig(
      name: "INTERNATIONAL",
      threshold: 2.0,
      exclusions: ["olympic", "olympics", "sport", "cricket", "football", "rugby", "tennis"],
      keywords: [
        TopicKeyword(keyword: "gaza", weight: 2.5),
        TopicKeyword(keyword: "palestine", weight: 2.0),
        TopicKeyword(keyword: "israel", weight: 1.5),
        TopicKeyword(keyword: "march for freedom", weight: 2.5),
        TopicKeyword(keyword: "ukraine", weight: 2.0),
        TopicKeyword(keyword: "war", weight: 1.5),
        TopicKeyword(keyword: "imperialism", weight: 2.0),
        TopicKeyword(keyword: "nato", weight: 1.5),
        TopicKeyword(keyword: "military", weight: 1.0),
        TopicKeyword(keyword: "occupation", weight: 1.5),
        TopicKeyword(keyword: "refugee", weight: 1.5),
        TopicKeyword(keyword: "refugees", weight: 1.5),
        TopicKeyword(keyword: "sanction", weight: 1.5),
        TopicKeyword(keyword: "sanctions", weight: 1.5),
        TopicKeyword(keyword: "middle east", weight: 1.5),
        TopicKeyword(keyword: "china", weight: 1.0),
        TopicKeyword(keyword: "usa", weight: 1.0),
        TopicKeyword(keyword: "united states", weight: 1.0),
        TopicKeyword(keyword: "europe", weight: 1.0),
      ],
    ),
    const TopicConfig(
      name: "LABOUR",
      threshold: 2.0,
      exclusions: ["funeral", "memorial", "obituary", "death", "sport"],
      keywords: [
        TopicKeyword(keyword: "cfmeu", weight: 2.5),
        TopicKeyword(keyword: "construction", weight: 1.0),
        TopicKeyword(keyword: "builders labour", weight: 2.5),
        TopicKeyword(keyword: "industrial", weight: 1.5),
        TopicKeyword(keyword: "industrial action", weight: 2.5),
        TopicKeyword(keyword: "industrial relations", weight: 2.0),
        TopicKeyword(keyword: "fair work", weight: 1.5),
        TopicKeyword(keyword: "award", weight: 1.0),
        TopicKeyword(keyword: "awards", weight: 1.0),
        TopicKeyword(keyword: "enterprise agreement", weight: 2.0),
        TopicKeyword(keyword: "enterprise agreements", weight: 2.0),
        TopicKeyword(keyword: "registered architect", weight: 1.0),
        TopicKeyword(keyword: "labour", weight: 1.0),
        TopicKeyword(keyword: "worker", weight: 1.0),
        TopicKeyword(keyword: "workers", weight: 1.0),
        TopicKeyword(keyword: "union", weight: 1.0),
        TopicKeyword(keyword: "unions", weight: 1.0),
        TopicKeyword(keyword: "strike", weight: 1.5),
        TopicKeyword(keyword: "wage", weight: 1.0),
        TopicKeyword(keyword: "wages", weight: 1.0),
        TopicKeyword(keyword: "pay", weight: 0.5),
        TopicKeyword(keyword: "pay rise", weight: 2.0),
        TopicKeyword(keyword: "pay rises", weight: 2.0),
        TopicKeyword(keyword: "minimum wage", weight: 2.0),
        TopicKeyword(keyword: "casual", weight: 1.0),
        TopicKeyword(keyword: "casualisation", weight: 2.0),
        TopicKeyword(keyword: "casual work", weight: 1.5),
        TopicKeyword(keyword: "full time", weight: 0.5),
        TopicKeyword(keyword: "full-time", weight: 0.5),
        TopicKeyword(keyword: "permanent", weight: 0.5),
        TopicKeyword(keyword: "job", weight: 0.5),
        TopicKeyword(keyword: "jobs", weight: 0.5),
        TopicKeyword(keyword: "employment", weight: 0.5),
        TopicKeyword(keyword: "unemployment", weight: 1.0),
        TopicKeyword(keyword: "layoff", weight: 1.5),
        TopicKeyword(keyword: "layoffs", weight: 1.5),
        TopicKeyword(keyword: "redundancy", weight: 1.5),
        TopicKeyword(keyword: "redundancies", weight: 1.5),
        TopicKeyword(keyword: "job cut", weight: 1.5),
        TopicKeyword(keyword: "job cuts", weight: 1.5),
        TopicKeyword(keyword: "job security", weight: 2.0),
        TopicKeyword(keyword: "workplace", weight: 0.5),
        TopicKeyword(keyword: "workplace safety", weight: 1.5),
        TopicKeyword(keyword: "safe work", weight: 1.5),
        TopicKeyword(keyword: "health and safety", weight: 1.5),
        TopicKeyword(keyword: "ohs", weight: 1.0),
        TopicKeyword(keyword: "whs", weight: 1.0),
        TopicKeyword(keyword: "lockout", weight: 2.0),
        TopicKeyword(keyword: "lock-out", weight: 2.0),
        TopicKeyword(keyword: "closed shop", weight: 2.0),
        TopicKeyword(keyword: "roster", weight: 0.5),
        TopicKeyword(keyword: "rosters", weight: 0.5),
        TopicKeyword(keyword: "shift", weight: 0.5),
        TopicKeyword(keyword: "shifts", weight: 0.5),
        TopicKeyword(keyword: "overtime", weight: 1.5),
        TopicKeyword(keyword: "penalty", weight: 1.0),
        TopicKeyword(keyword: "penalties", weight: 1.0),
        TopicKeyword(keyword: "entitlement", weight: 1.0),
        TopicKeyword(keyword: "entitlements", weight: 1.0),
        TopicKeyword(keyword: "agreement", weight: 0.5),
        TopicKeyword(keyword: "agreements", weight: 0.5),
        TopicKeyword(keyword: "negotiation", weight: 1.5),
        TopicKeyword(keyword: "negotiations", weight: 1.5),
        TopicKeyword(keyword: "collective", weight: 1.0),
        TopicKeyword(keyword: "collective bargaining", weight: 2.0),
        TopicKeyword(keyword: "employer", weight: 0.5),
        TopicKeyword(keyword: "employers", weight: 0.5),
        TopicKeyword(keyword: "corporation", weight: 0.5),
        TopicKeyword(keyword: "companies", weight: 0.5),
        TopicKeyword(keyword: "company", weight: 0.5),
        TopicKeyword(keyword: "private", weight: 0.5),
        TopicKeyword(keyword: "privatisation", weight: 2.0),
        TopicKeyword(keyword: "privatization", weight: 2.0),
        TopicKeyword(keyword: "privatise", weight: 2.0),
        TopicKeyword(keyword: "privatize", weight: 2.0),
        TopicKeyword(keyword: "contractor", weight: 1.0),
        TopicKeyword(keyword: "contractors", weight: 1.0),
        TopicKeyword(keyword: "labour hire", weight: 2.0),
        TopicKeyword(keyword: "labour-hire", weight: 2.0),
        TopicKeyword(keyword: "exploitation", weight: 2.0),
        TopicKeyword(keyword: "exploited", weight: 2.0),
        TopicKeyword(keyword: "decent rights", weight: 2.0),
        TopicKeyword(keyword: "decent jobs", weight: 2.0),
        TopicKeyword(keyword: "standard", weight: 0.5),
        TopicKeyword(keyword: "standards", weight: 0.5),
        TopicKeyword(keyword: "rights", weight: 0.5),
        TopicKeyword(keyword: "worker rights", weight: 2.0),
        TopicKeyword(keyword: "worker's rights", weight: 2.0),
        TopicKeyword(keyword: "unionism", weight: 1.5),
        TopicKeyword(keyword: "unionize", weight: 1.5),
        TopicKeyword(keyword: "unionise", weight: 1.5),
        TopicKeyword(keyword: "organize", weight: 1.0),
        TopicKeyword(keyword: "organise", weight: 1.0),
        TopicKeyword(keyword: "solidarity", weight: 1.5),
      ],
    ),
    const TopicConfig(
      name: "MUTUAL AID",
      threshold: 2.0,
      exclusions: ["sport", "recreation"],
      keywords: [
        TopicKeyword(keyword: "mutual aid", weight: 3.0),
        TopicKeyword(keyword: "solidarity", weight: 2.0),
        TopicKeyword(keyword: "community", weight: 1.0),
        TopicKeyword(keyword: "co-op", weight: 2.0),
        TopicKeyword(keyword: "cooperative", weight: 2.0),
        TopicKeyword(keyword: "cooperatives", weight: 2.0),
        TopicKeyword(keyword: "food share", weight: 2.0),
        TopicKeyword(keyword: "free food", weight: 2.0),
        TopicKeyword(keyword: "food relief", weight: 2.0),
        TopicKeyword(keyword: "food bank", weight: 2.0),
        TopicKeyword(keyword: "rent relief", weight: 2.0),
        TopicKeyword(keyword: "rent crisis", weight: 2.0),
        TopicKeyword(keyword: "eviction", weight: 2.0),
        TopicKeyword(keyword: "evictions", weight: 2.0),
        TopicKeyword(keyword: "homeless", weight: 1.5),
        TopicKeyword(keyword: "homelessness", weight: 2.0),
        TopicKeyword(keyword: "housing crisis", weight: 2.0),
        TopicKeyword(keyword: "social housing", weight: 2.0),
        TopicKeyword(keyword: "affordable housing", weight: 2.0),
        TopicKeyword(keyword: "charity", weight: 1.0),
        TopicKeyword(keyword: "charitable", weight: 1.0),
      ],
    ),
    const TopicConfig(
      name: "PARLIAMENT",
      threshold: 2.0,
      exclusions: ["olympic", "olympics", "sport", "cricket", "football", "rugby", "tennis", "funeral", "memorial"],
      keywords: [
        TopicKeyword(keyword: "albanese", weight: 2.0),
        TopicKeyword(keyword: "dutton", weight: 2.0),
        TopicKeyword(keyword: "labor", weight: 1.5),
        TopicKeyword(keyword: "liberal", weight: 1.0),
        TopicKeyword(keyword: "national", weight: 1.0),
        TopicKeyword(keyword: "green", weight: 1.0),
        TopicKeyword(keyword: "teal", weight: 1.5),
        TopicKeyword(keyword: "parliament", weight: 1.5),
        TopicKeyword(keyword: "parliamentary", weight: 1.5),
        TopicKeyword(keyword: "government", weight: 1.0),
        TopicKeyword(keyword: "senate", weight: 1.5),
        TopicKeyword(keyword: "election", weight: 1.5),
        TopicKeyword(keyword: "elections", weight: 1.5),
        TopicKeyword(keyword: "bill", weight: 1.5),
        TopicKeyword(keyword: "bills", weight: 1.5),
        TopicKeyword(keyword: "legislation", weight: 1.5),
        TopicKeyword(keyword: "policy", weight: 1.0),
        TopicKeyword(keyword: "policies", weight: 1.0),
        TopicKeyword(keyword: "minister", weight: 1.0),
        TopicKeyword(keyword: "ministers", weight: 1.0),
        TopicKeyword(keyword: "mp", weight: 1.0),
        TopicKeyword(keyword: "mps", weight: 1.0),
        TopicKeyword(keyword: "seat", weight: 0.5),
        TopicKeyword(keyword: "seats", weight: 0.5),
        TopicKeyword(keyword: "poll", weight: 1.0),
        TopicKeyword(keyword: "polls", weight: 1.0),
        TopicKeyword(keyword: "preference", weight: 1.0),
        TopicKeyword(keyword: "preferences", weight: 1.0),
        TopicKeyword(keyword: "two-party", weight: 1.5),
        TopicKeyword(keyword: "preferential", weight: 1.0),
        TopicKeyword(keyword: "campaign", weight: 1.0),
        TopicKeyword(keyword: "campaigning", weight: 1.0),
        TopicKeyword(keyword: "rally", weight: 1.0),
        TopicKeyword(keyword: "rallies", weight: 1.0),
      ],
    ),
    const TopicConfig(
      name: "PRAXIS",
      threshold: 2.0,
      exclusions: ["sport", "recreation", "funeral", "memorial"],
      keywords: [
        TopicKeyword(keyword: "protest", weight: 2.0),
        TopicKeyword(keyword: "protests", weight: 2.0),
        TopicKeyword(keyword: "activism", weight: 2.0),
        TopicKeyword(keyword: "activist", weight: 1.5),
        TopicKeyword(keyword: "activists", weight: 1.5),
        TopicKeyword(keyword: "demonstration", weight: 2.0),
        TopicKeyword(keyword: "demonstrations", weight: 2.0),
        TopicKeyword(keyword: "rally", weight: 1.5),
        TopicKeyword(keyword: "rallies", weight: 1.5),
        TopicKeyword(keyword: "march", weight: 1.5),
        TopicKeyword(keyword: "marching", weight: 1.5),
        TopicKeyword(keyword: "occupation", weight: 1.5),
        TopicKeyword(keyword: "occupy", weight: 1.5),
        TopicKeyword(keyword: "occupying", weight: 1.5),
        TopicKeyword(keyword: "sit-in", weight: 2.0),
        TopicKeyword(keyword: "sit in", weight: 2.0),
        TopicKeyword(keyword: "blockade", weight: 2.0),
        TopicKeyword(keyword: "blockading", weight: 2.0),
        TopicKeyword(keyword: "picket", weight: 2.0),
        TopicKeyword(keyword: "picketing", weight: 2.0),
        TopicKeyword(keyword: "pickets", weight: 2.0),
        TopicKeyword(keyword: "civil disobedience", weight: 2.5),
        TopicKeyword(keyword: "resistance", weight: 1.5),
        TopicKeyword(keyword: "resisting", weight: 1.5),
        TopicKeyword(keyword: "uprising", weight: 2.0),
        TopicKeyword(keyword: "revolution", weight: 1.5),
        TopicKeyword(keyword: "revolutionary", weight: 1.5),
        TopicKeyword(keyword: "solidarity", weight: 1.5),
        TopicKeyword(keyword: "organize", weight: 1.0),
        TopicKeyword(keyword: "organise", weight: 1.0),
        TopicKeyword(keyword: "organizing", weight: 1.0),
        TopicKeyword(keyword: "organising", weight: 1.0),
      ],
    ),
    const TopicConfig(
      name: "TECHNOLOGY",
      threshold: 2.0,
      exclusions: ["app", "application", "software", "digital", "online", "website", "gadget", "device", "phone", "mobile", "computer", "internet", "social media", "platform", "robot", "blockchain", "crypto", "nft", "metaverse", "virtual reality", "augmented reality", "cloud", "server", "hack", "malware", "virus", "gdpr", "facial recognition", "biometric"],
      keywords: [
        TopicKeyword(keyword: "technology", weight: 1.5),
        TopicKeyword(keyword: "artificial intelligence", weight: 3.0),
        TopicKeyword(keyword: "ai", weight: 2.0),
        TopicKeyword(keyword: "machine learning", weight: 2.5),
        TopicKeyword(keyword: "automation", weight: 2.0),
        TopicKeyword(keyword: "robotics", weight: 2.0),
        TopicKeyword(keyword: "surveillance", weight: 2.0),
        TopicKeyword(keyword: "privacy", weight: 1.5),
        TopicKeyword(keyword: "cybersecurity", weight: 2.0),
        TopicKeyword(keyword: "cyber", weight: 1.0),
        TopicKeyword(keyword: "data", weight: 0.5),
        TopicKeyword(keyword: "tech", weight: 1.0),
        TopicKeyword(keyword: "startup", weight: 1.0),
        TopicKeyword(keyword: "innovation", weight: 1.0),
        TopicKeyword(keyword: "tech regulation", weight: 2.0),
        TopicKeyword(keyword: "big tech", weight: 2.0),
        TopicKeyword(keyword: "silicon valley", weight: 1.5),
      ],
    ),
  ];
}